# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ab5802aea799ca7e4ce6e7b8b2d67a99e3d578f4be8f49785692d05d7e0a6c4d86cc7ed2d9f0b3b369373486a006822fd376627ca15794f563bade9ecbfe99

test:
  secret_key_base: c756717a3efed7ce0d5198ac79069e710e6e8f2660b0fb402716ddfd8b9261e3fa488fe9055d2bdbb6a76bd70d741c009e16ccb09ec7a718f5f55394c5a4c7de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
